### ISSUE TITLE
GPU configuration for mesonet 

### ISSUE THREAD

**Issue by Fatemeh-Yousefi** [bf777/MesoNet#43]
Thank you for sharing the code!

I’m currently trying to set up Mesonet on my PC, but I’ve encountered an issue. While Deeplabcut can successfully use my GPU, Mesonet seems to only work on the CPU. To clarify, here are the details of my setup:

Deeplabcut: 3.0.0r5
TensorFlow: 2.13
GPU: NVIDIA GeForce RTX 3060
CUDA: 11.8
I’ve tried different versions of TensorFlow, but the issue persists.

I would greatly appreciate any guidance you could provide!

**Comment by bf777** [comment]
Addressed offline; image warping parameters now written out as per #46.
