### ISSUE TITLE
Installing on windows

### ISSUE THREAD

**Issue by NathanTBurgess** [bf777/MesoNet#47]
Hello! I am attempting to install this on my windows computer but I am running int an issue getting it to work with my GPU.

I think the issue is that MesoNet seems to work with Tensorflow 2.12 but Deeplab cut only works with tensorflow up to version 2.10 on windows. 

I am attempting to get it working on a linux machine now but was wondering if you have any input. Does MesnoNet no longer support GPU usage on Windows?

Thank you

**Comment by bf777** [comment]
Hi @NathanTBurgess, MesoNet should work on Windows - the tensorflow issue mismatch has been a persistent issue. Could you try installing `tensorflow==2.10` after installing MesoNet and see if that helps address the issue? Additionally, if you could share any error messages that come up, that would help me diagnose the issue more precisely - thank you.

**Comment by NathanTBurgess** [comment]
I got it working!

I needed to put some more work into using the right CUDNN version and placing the files in the correct places. Thanks!
